apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels: 
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      env: production
      